import mongoose from 'mongoose';
import FAQ from '../server/src/models/FAQ.model.js';
import { rebuildCorpus, buildFAQText, CORPUS_FAQ } from '../server/src/services/vector/embedding.service.js';
import { insertFAQVector } from '../server/src/services/vector/faq.vector.service.js';
import logger from '../server/src/utils/logger.js';

const faqs = [
  {"id":"1_about_the_internship_001","category":"1. About the internship","question":"1.1 What is the Vicharanashala internship?","answer":"A two-month internship run by Vicharanashala, a research lab at IIT Ropar. You will work on a real open-source project under a mentor, after a short training phase tailored to where you already are. The internship is free — we do not charge, and the work is real.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"1_about_the_internship_002","category":"1. About the internship","question":"1.2 What is VINS?","answer":"VINS is the Vicharanashala Internship — an online programme open to anyone who clears our interview. The work is real open-source contribution under a mentor, the certificate is from the Vicharanashala Lab for Education Design at IIT Ropar, and the programme itself is free (we charge nothing). There is no stipend.\nIf you are seeing a yellow VINS panel on your result page, you are selected.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"1_about_the_internship_003","category":"1. About the internship","question":"1.3 What are the phases of VINS, and what do the badges mean?","answer":"VINS is structured as four phases. Each one is marked by a badge — a small token of where you are in the journey.\nBronze (Phase 1) — a short training period at the start, planned around what you already know. If you arrive already comfortable with the basics, your mentor may skip Bronze and put you straight on to the project.\nSilver (Phase 2) — the main work. You contribute to a real open-source project under a Vicharanashala mentor. Finishing Bronze and Silver completes your internship and earns the certificate.\nGold (Phase 3) — a recognition awarded during Silver if your contribution stands on its own as a meaningful feature, not just a small fix.\nPlatinum (Phase 4) — a standing invitation to come back and visit the lab — a short trip — any time during the year after your internship ends. We help with travel through a small visit stipend.\nMost interns finish at Bronze + Silver, and that is exactly what the certificate is for. Gold and Platinum are extras you can pick up if your work makes the case for them. Either way, you walk away with a real open-source contribution to your name and a mentor who knows you well.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"1_about_the_internship_004","category":"1. About the internship","question":"1.4 Who is the internship for? Are alumni eligible?","answer":"The internship is for currently-enrolled students at any college or university — undergraduate, postgraduate, or doctoral. The NOC requirement is the practical reflection of this: we ask for institutional consent that you can commit your time to this internship.\nCandidates who have already graduated and are not currently enrolled in any programme are not eligible for this cycle. If you re-enrol later (higher studies, etc.), you are very welcome to apply again in a future cycle.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"1_about_the_internship_005","category":"1. About the internship","question":"1.5 Is this the same as IIT Ropar's official Summer Research Internship?","answer":"No. Summership 2026 is a VLED Lab initiative. The certificate is issued by the Vicharanashala Lab for Education Design, not centrally by the institute. IIT Ropar runs a separate institutional summer research internship through its own office. Do not represent Summership 2026 as equivalent to that programme.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"1_about_the_internship_006","category":"1. About the internship","question":"1.6 I have to attend my class tomorrow/today/some day can I take leave","answer":"Leave is not permitted. If you are also attending classes or exams, you will be relieved from the internship immediately and will need to join the next batch when it starts.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"2_timing_and_dates_001","category":"2. Timing and dates","question":"2.1 When can I start?","answer":"You can start any time in 2026 — VINS is flexible on the start date — but there are two things you must hold in mind together, and one strong recommendation.\nThe hard rule: Your internship must finish by 31 December 2026. That date is non-negotiable. Whatever start you pick, your end date (your start + 2 months, with up to 1 month grace) must land on or before 31 December 2026.\nThe strong recommendation: start as soon as possible. The earlier you join, the more of the May–July main cohort you catch.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"2_timing_and_dates_002","category":"2. Timing and dates","question":"2.2 How long is the internship?","answer":"Two months from your chosen start date, with an optional one-month grace period if you need it. End must land on or before 31 December 2026.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"2_timing_and_dates_003","category":"2. Timing and dates","question":"2.3 Can I start in July, August or later if I have exams now?","answer":"Yes — but only if your exams genuinely make an earlier start impossible. Wait until your exams are done, then opt in and start. Do not attempt to juggle this internship with ongoing exams. Make sure your chosen start date plus 2 months (or 3 with grace) lands on or before 31 December 2026.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"2_timing_and_dates_004","category":"2. Timing and dates","question":"2.4 Can I start with the cohort and take a relaxation during my exam window?","answer":"No. This is not an arrangement we offer.\nVINS is a full-attention internship — six to ten hours a day, sometimes more. Splitting that with college exams damages both sides.\nIf your exams fall inside the cohort duration, defer your start to after your exams end.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"2_timing_and_dates_005","category":"2. Timing and dates","question":"2.5 Can I take leave or get an exemption during the internship for an exam scheduled in June?","answer":"The attendance rule is firm — the 55-day continuous window is a non-negotiable part of the internship, and we cannot offer an exemption for an exam during this period.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"2_timing_and_dates_006","category":"2. Timing and dates","question":"2.6 Are orientation session recordings shared with interns?","answer":"Recordings of the sessions will not be provided. However, we may provide access to an abridged version of a talk or session if we consider it important. We do not guarantee this for every session.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"3_noc_no_objection_certificate_001","category":"3. NOC (No Objection Certificate)","question":"3.1 What dates do I put on the NOC?","answer":"Default: your chosen start date to your start + 2 months (with up to 1 month grace), ensuring the end date is on or before 31 December 2026. Pick the earliest start date you can realistically make.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"3_noc_no_objection_certificate_002","category":"3. NOC (No Objection Certificate)","question":"3.2 Who can sign the NOC?","answer":"Any authorised signatory at your college: HOD, Acting HOD (during holidays), Principal, Dean, Director, or Training & Placement Officer. For dual-degree students, either institution can sign — pick whichever is easier.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"3_noc_no_objection_certificate_003","category":"3. NOC (No Objection Certificate)","question":"3.3 When do I submit the NOC? Is the deadline hard?","answer":"There is no specific calendar cut-off date by which the NOC must be uploaded — but your internship cannot formally begin until your official institutional NOC has been uploaded and validated by us. Submit your signed NOC as early as possible.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"3_noc_no_objection_certificate_004","category":"3. NOC (No Objection Certificate)","question":"3.4 What format should I use? Do I need to design it myself?","answer":"No — we provide a printable NOC format. Once your result is out and you log in to samagama.in, you will see a Download blank NOC button on your dashboard.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"3_noc_no_objection_certificate_005","category":"3. NOC (No Objection Certificate)","question":"3.5 What if my college gives me an NOC in their own format?","answer":"A college's own NOC format is acceptable, as long as all required entries are present: the signing authority's handwritten signature, name, designation, official email address and phone number, your full name and internship period, and your signature.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"3_noc_no_objection_certificate_006","category":"3. NOC (No Objection Certificate)","question":"3.6 Does it need to be signed by hand?","answer":"Yes. Three things are required: the authorised signatory's handwritten signature, the institutional rubber stamp/seal applied in the designated area, and the signatory's email address filled in the designated field.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"3_noc_no_objection_certificate_007","category":"3. NOC (No Objection Certificate)","question":"3.7 Can my HOD email the NOC instead of signing a printout?","answer":"Yes — there is a fully-equivalent email-forward path. From your dashboard, download the text NOC, fill in the student-side fields, then email the file to your HOD and ask them to forward it to sudarshan@iitrpr.ac.in from their official institutional email address.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"3_noc_no_objection_certificate_008","category":"3. NOC (No Objection Certificate)","question":"3.8 How do I download and upload the NOC?","answer":"Both happen on your dashboard at samagama.in once your result is out. You will see a NOC section with two buttons: Download blank NOC and Upload signed NOC (PDF).","source":"samagama_faq","chunk_type":"faq"},
  {"id":"3_noc_no_objection_certificate_009","category":"3. NOC (No Objection Certificate)","question":"3.9 What if my NOC is not formally verified?","answer":"NOC verification takes time — typically anywhere between an hour and one full working day. If you need your offer letter sooner, upload a self-declaration on your dashboard and a provisional offer letter will be issued immediately.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"3_noc_no_objection_certificate_010","category":"3. NOC (No Objection Certificate)","question":"3.10 My online course (Masai, NPTEL, Coursera, etc.) won't issue an NOC. What do I do?","answer":"The internship is open only to candidates currently enrolled in a full-time degree programme. Online-only courses do not by themselves make a candidate eligible. If you are concurrently enrolled in a full-time degree programme, please obtain a No Due/No Objection certificate from that college.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"3_noc_no_objection_certificate_011","category":"3. NOC (No Objection Certificate)","question":"3.11 My HOD wants written confirmation before signing my NOC. What do I show them?","answer":"Your selection is already confirmed the moment your yellow VINS result panel appears on your samagama.in dashboard. If your HOD insists on a document, upload a self-declaration on your dashboard to get a provisional offer letter on Vicharanashala letterhead immediately.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"3_noc_no_objection_certificate_012","category":"3. NOC (No Objection Certificate)","question":"3.12 Can Prof. Sudarshan Iyengar sign my NOC?","answer":"Your NOC must be signed by an authorised signatory at the institution where you are enrolled. Sudarshan Iyengar is a faculty member at IIT Ropar and cannot sign your NOC in a personal capacity.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"4_selection_offer_letter_and_certificate_001","category":"4. Selection, offer letter, and certificate","question":"4.1 How do I know I am selected?","answer":"If you can see your yellow VINS result panel on samagama.in, you are selected. There is no separate selection step or confirmation email.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"4_selection_offer_letter_and_certificate_002","category":"4. Selection, offer letter, and certificate","question":"4.2 How do I opt into VINS?","answer":"Tell Yaksha in the chat: I want to take up the online internship without stipend. Yaksha will confirm. Opting in is the selection — no separate confirmation email is sent.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"4_selection_offer_letter_and_certificate_003","category":"4. Selection, offer letter, and certificate","question":"4.3 When do I get the offer letter?","answer":"Your offer letter is issued automatically. If you upload a self-declaration (the fast path), a provisional offer letter is issued immediately. If you upload your signed NOC first, your offer letter is issued automatically once the NOC is validated.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"4_selection_offer_letter_and_certificate_004","category":"4. Selection, offer letter, and certificate","question":"4.4 Will I get a certificate?","answer":"Yes — every intern who completes the internship gets a certificate from Vicharanashala, IIT Ropar. The internship is genuinely demanding; candidates who drop out mid-way do not get a certificate.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"4_selection_offer_letter_and_certificate_005","category":"4. Selection, offer letter, and certificate","question":"4.5 How do I confirm my internship dates?","answer":"Once you have opted into VINS, log in to samagama.in. On the dashboard, you will see a yellow card titled Confirm your internship dates. Edit them to your earliest realistic start — your end must be on or before 31 December 2026.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"4_selection_offer_letter_and_certificate_006","category":"4. Selection, offer letter, and certificate","question":"4.6 I am a minor/major in AI student from IIT Ropar — can I join?","answer":"Minor/Major in AI course from IIT Ropar is a certification course and there will be a different track of internship equivalent to them. For you to be part of this internship programme you should be a registered student in a UG/PG programme with some university.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"4_selection_offer_letter_and_certificate_007","category":"4. Selection, offer letter, and certificate","question":"4.7 How do I accept the offer letter?","answer":"Reply All on the offer-letter thread and paste the exact acceptance statement with your full name inserted and a date added: I, [Full Name], confirm that I have read, understood, and accepted all terms, conditions, and obligations set out in this offer letter and in the program FAQ at samagama.in. I formally accept the offer of Summer Internship 2026.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"4_selection_offer_letter_and_certificate_008","category":"4. Selection, offer letter, and certificate","question":"4.8 What if I reply without using the exact acceptance format?","answer":"The offer is withdrawn, effective immediately, with no further correspondence. The withdrawal is final. This is a deliberate policy — the acceptance statement is the first attention-to-detail check of the internship.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"4_selection_offer_letter_and_certificate_009","category":"4. Selection, offer letter, and certificate","question":"4.9 I received a withdrawal email. Can it be reversed?","answer":"There is an appeal path. Send a fresh email to sudarshansudarshan@gmail.com with subject exactly: Request to Reconsider: Confirmation Reply Error. In the body, state an apology and the reason. If genuine, we will respond within 24 hours.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"4_selection_offer_letter_and_certificate_010","category":"4. Selection, offer letter, and certificate","question":"4.10 What happens after I send my acceptance? My dashboard doesn't update.","answer":"The dashboard tracks your NOC, internship dates, and offer letter — it does not track the acceptance email. We process acceptance emails manually. If your reply was compliant, no further action is needed from your side.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"4_selection_offer_letter_and_certificate_011","category":"4. Selection, offer letter, and certificate","question":"4.11 Can I change my internship dates?","answer":"Before the offer letter is issued: yes — open the Confirm Internship Dates card on your dashboard and edit at any time. After the offer letter is issued: no. Dates are final and will not be changed.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"4_selection_offer_letter_and_certificate_012","category":"4. Selection, offer letter, and certificate","question":"4.12 When and how do I get the Zoom link for the kickoff meeting?","answer":"The kickoff orientation is held for the main summer cohort only. The Zoom link is delivered through email to your registered samagama.in address and your Yaksha chat portal.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"4_selection_offer_letter_and_certificate_013","category":"4. Selection, offer letter, and certificate","question":"4.13 My NOC is not ready but my start date is approaching. What do I do?","answer":"Upload a self-declaration on your dashboard. A provisional offer letter is issued immediately, which you can show your HOD to get your NOC signed. Your start date cannot be honoured until your official institutional NOC is uploaded and validated.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"4_selection_offer_letter_and_certificate_014","category":"4. Selection, offer letter, and certificate","question":"4.14 When does my internship actually begin?","answer":"Your internship begins on the start date you confirmed on the dashboard, provided your official institutional NOC has been uploaded and validated by us by then. There is no separate notification on the day itself; the start date is the start date.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"4_selection_offer_letter_and_certificate_015","category":"4. Selection, offer letter, and certificate","question":"4.15 Can I switch from VINS (online) to VISE (offline) after being selected?","answer":"The two tracks are finalised at the interview stage, and we do not move candidates between them. VISE has a fixed on-campus capacity — once the shortlist is set, it stays set.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"4_selection_offer_letter_and_certificate_016","category":"4. Selection, offer letter, and certificate","question":"4.16 Can I change my internship dates after the offer letter?","answer":"No. Once your offer letter has been issued, the dates you confirmed are final. They will not be changed at this stage.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"4_selection_offer_letter_and_certificate_017","category":"4. Selection, offer letter, and certificate","question":"4.17 How do I get the link for the daily Zoom standups? Are they mandatory?","answer":"Daily Zoom standup links are posted in the Announcements section on your samagama.in dashboard at least 1 hour before the session. Attending the daily standups is mandatory for all interns.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"4_selection_offer_letter_and_certificate_018","category":"4. Selection, offer letter, and certificate","question":"4.18 How do I provide my Zoom ID, and why does it matter?","answer":"On your dashboard, just before Start the internship, you'll see a step called Provide your Zoom ID. Enter the exact email address linked to your Zoom account. We match your live-session attendance using this email.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"4_selection_offer_letter_and_certificate_019","category":"4. Selection, offer letter, and certificate","question":"4.19 I saved the wrong Zoom ID — can I change it?","answer":"Once saved, your Zoom ID is final and cannot be changed by you. If you are certain you entered the wrong email, type #escalate in the chat with your correct Zoom email, and our team will review and correct it for you.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"5_work_mentorship_and_projects_001","category":"5. Work, mentorship, and projects","question":"5.1 What will I work on?","answer":"A real open-source project from Vicharanashala's portfolio — assigned based on your background and the lab's current needs. Areas range across AI/ML, web development, NLP, computer vision, agriculture-tech, education-tech, and open-source infrastructure.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"5_work_mentorship_and_projects_002","category":"5. Work, mentorship, and projects","question":"5.2 How many hours per day?","answer":"Plan for 6 to 10 hours a day, sometimes more during the build phase. This is a full-time internship for the two-month window. Most candidates who drop out are juggling something else.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"5_work_mentorship_and_projects_003","category":"5. Work, mentorship, and projects","question":"5.3 Who is my mentor?","answer":"You will work with the lab's research and engineering team. The exact mentor depends on the project. The model is fluid — you will get help from a senior researcher one day, a peer the next, and someone else for a different question.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"5_work_mentorship_and_projects_004","category":"5. Work, mentorship, and projects","question":"5.4 Is there a stipend?","answer":"No. The internship is unpaid. Stellar performers may be recognised with a discretionary stipend at the lab's option, but this is not promised or expected.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"5_work_mentorship_and_projects_005","category":"5. Work, mentorship, and projects","question":"5.5 Do I need my own laptop? Should I preload any software?","answer":"Yes — a personal laptop is required. We prefer Linux or macOS. If you use Windows, please install WSL or a terminal that can SSH and run Unix-style commands.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"5_work_mentorship_and_projects_006","category":"5. Work, mentorship, and projects","question":"5.6 I am using a different email on GitHub/Zoom/the learning platform. Is that okay?","answer":"No. Your registered email is your sole identifier across all programme platforms. Mismatches between platforms cannot be retroactively corrected.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"5_work_mentorship_and_projects_007","category":"5. Work, mentorship, and projects","question":"5.7 Why has my mentor not been assigned yet, or contacted me on day 1?","answer":"Mentors are not assigned on day 1. You will be assigned a mentor when you move on to the project phase of VINS, which comes later in the timeline. Before that, you must complete the mandatory coursework of the Bronze phase.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"6_code_of_conduct_communication_channels_001","category":"6. Code of conduct — communication channels","question":"6.1 What are the official communication channels?","answer":"Official channels in order: (1) Announcements section on samagama.in, (2) Yaksha chat on samagama.in, (3) Discussion forum, (4) Email to sudarshansudarshan@gmail.com as a last resort. WhatsApp support is cancelled. Unofficial groups are strictly prohibited and will lead to immediate termination of your internship.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"7_interviews_related_001","category":"7. Interviews Related","question":"7.1 My interview is not marked as complete on the dashboard — what do I do?","answer":"A data-sync issue sometimes occurs where the chat session closes but the interview record doesn't update to completed. The team will check your record and manually mark it as complete if needed. If you dont hear from us, please write to us on sudarshansudarshan@gmail.com","source":"samagama_faq","chunk_type":"faq"},
  {"id":"8_certificate_001","category":"8. Certificate","question":"8.1 Does Vicharanashala send a grade report or evaluation to my university?","answer":"Vicharanashala does not send formal evaluation or grade reports to universities — that process is between you and your college. The certificate issued upon completion is the document you can submit to your college or placement office for credit.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"8_certificate_002","category":"8. Certificate","question":"8.2 Does the certificate specify whether it was online or offline?","answer":"The certificate you receive on completing the internship is the same for both tracks. It is issued by Vicharanashala, IIT Ropar, and does not specify whether you completed it online or on campus.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"8_certificate_003","category":"8. Certificate","question":"8.3 Will the completion certificate be a physical hardcopy or an e-certificate?","answer":"The completion certificate is issued as an e-certificate — you download it from your dashboard on samagama.in after completing both Bronze and Silver. We do not print and mail physical copies.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"8_certificate_004","category":"8. Certificate","question":"8.4 Is there a WhatsApp group for candidates during the internship?","answer":"No. See section 6.1 for the official communication channels.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"9_rosetta_your_internship_journal_001","category":"9. Rosetta — your internship journal","question":"9.1 What is Rosetta?","answer":"Rosetta is your internship journal — a 65-day document, one entry per day, every day, for the full duration of Summership 2026. You write in it daily, keep it privately, and submit it at the end of the internship as one of your completion requirements.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"9_rosetta_your_internship_journal_002","category":"9. Rosetta — your internship journal","question":"9.2 Why does this exist? Is it just busywork?","answer":"No. For you: Most people go through an intense experience and carry it without processing it. The journal builds articulation, one day at a time. For us: When you submit Rosetta at the end, it gives us qualitative insight into your experience that no survey or evaluation can capture.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"9_rosetta_your_internship_journal_003","category":"9. Rosetta — your internship journal","question":"9.3 What is a thinking routine?","answer":"Each day in Rosetta has a thinking routine — a short framework that gives your reflection a specific shape. Examples: 3-2-1 (3 things you engaged with, 2 questions on your mind, 1 surprise), Muddy/Clear (what is sharp, what is still foggy), What? So What? Now What?","source":"samagama_faq","chunk_type":"faq"},
  {"id":"9_rosetta_your_internship_journal_004","category":"9. Rosetta — your internship journal","question":"9.4 How do I get my Rosetta journal?","answer":"Your journal will be shared with you as a Google Doc template link during orientation. Open the link, make a copy to your own Google Drive, rename it Rosetta — [Your Name] — Summership 2026, and that copy is yours for the full 65 days.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"9_rosetta_your_internship_journal_005","category":"9. Rosetta — your internship journal","question":"9.5 How do I use it day to day?","answer":"Open your Rosetta Google Doc, scroll to the entry for today's day number, fill in the date, read the thinking routine name and its one-line description, answer the three prompts in the writing boxes below, close it and get on with your day. That is it.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"9_rosetta_your_internship_journal_006","category":"9. Rosetta — your internship journal","question":"9.6 How long should each entry be?","answer":"There is no minimum or maximum word count. A good entry is one that is honest and specific. Three to five sentences per prompt is usually enough. What is not acceptable: one-word answers, copy-pasted text, vague non-answers, or anything that reads like it was generated by an AI.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"9_rosetta_your_internship_journal_007","category":"9. Rosetta — your internship journal","question":"9.7 What is the one rule?","answer":"Write what is true. Not what sounds impressive. Not what you think we want to read. Not a polished summary of the day. If you hated today written that. We will know immediately if an entry reads like an LLM wrote it. Do not do that.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"9_rosetta_your_internship_journal_008","category":"9. Rosetta — your internship journal","question":"9.8 Can I use ChatGPT or any AI tool to write my entries?","answer":"No. This is the one firm rule of Rosetta. The journal is a record of your thinking, not a demonstration of what an AI can produce on your behalf. Entries that read as AI-generated will not be counted toward your completion requirement.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"9_rosetta_your_internship_journal_009","category":"9. Rosetta — your internship journal","question":"9.9 What if I miss a day?","answer":"Fill it in as soon as you can. Write the actual date you are filling it in, not the date of the missed entry. Be honest about the fact that you are writing it late and why. A late honest entry is always better than no entry.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"9_rosetta_your_internship_journal_010","category":"9. Rosetta — your internship journal","question":"9.10 Will anyone read my journal during the internship?","answer":"No. We will not access your journal during the 65 days. You write it, you keep it, it is yours. The only time we read it is after you submit it at the end of the internship.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"9_rosetta_your_internship_journal_011","category":"9. Rosetta — your internship journal","question":"9.11 Can the prompts change mid-internship?","answer":"Occasionally we may update a prompt for a specific day. When this happens, we will announce it in the Announcements section on samagama.in before that day begins.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"9_rosetta_your_internship_journal_012","category":"9. Rosetta — your internship journal","question":"9.12 How do I submit Rosetta at the end?","answer":"On or before Day 65, share your Rosetta Google Doc with the programme coordinator's email address (shared during wrap-up week). Set sharing permission to Viewer. Make sure your name is in the document title, all 65 entries have been filled in, and your cover page has your name, product, and team filled in.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"9_rosetta_your_internship_journal_013","category":"9. Rosetta — your internship journal","question":"9.13 I have a question about Rosetta that is not answered here. What do I do?","answer":"Ask Yaksha first. If Yaksha cannot answer it, escalate to your programme coordinator.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"9_rosetta_your_internship_journal_014","category":"9. Rosetta — your internship journal","question":"9.14 My college requires a written confirmation that the internship is self-paced — what document can I share?","answer":"This is not a self paced internship, but a very rigorous one which is time demanding. It is not permitted for one to be part of any other activity during this period.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"10_phase_1_coursework_vibe_lms_and_live_sessions_001","category":"10. Phase 1 — coursework, Vibe LMS, and live sessions","question":"10.1 I've previously interned with VLED — am I exempt from any coursework?","answer":"Yes — partially. If you previously interned with VLED and completed the MERN Stack coursework, you don't need to repeat it this cycle. However, the AI Fundamentals course is mandatory for everyone, including returning interns.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"10_phase_1_coursework_vibe_lms_and_live_sessions_002","category":"10. Phase 1 — coursework, Vibe LMS, and live sessions","question":"10.2 How do I register for the AI Fundamentals course on Vibe?","answer":"Click the AI Fundamentals registration link posted in the Announcements section on samagama.in at Phase 1 launch. You'll be redirected to the Vibe sign-in page. Create an account using the same Gmail you used to register on Samagama, complete the registration form and submit.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"10_phase_1_coursework_vibe_lms_and_live_sessions_003","category":"10. Phase 1 — coursework, Vibe LMS, and live sessions","question":"10.3 I registered on Vibe with a different email than my Samagama email — is that OK?","answer":"Please use the same email on both platforms. The one exception: Vibe requires a Gmail address for signup. If your Samagama email is not Gmail, you may use any Gmail of yours to register on Vibe. Then tell Yaksha using the tag: #vibe-email your-gmail@gmail.com","source":"samagama_faq","chunk_type":"faq"},
  {"id":"10_phase_1_coursework_vibe_lms_and_live_sessions_004","category":"10. Phase 1 — coursework, Vibe LMS, and live sessions","question":"10.4 Are live sessions mandatory if I'm on the viva route?","answer":"Yes — live sessions are mandatory for every intern, regardless of path. Whether you're on the coursework track, MERN-exempt, or have cleared the viva and moved to Phase 2, you're expected to attend every live session.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"10_phase_1_coursework_vibe_lms_and_live_sessions_005","category":"10. Phase 1 — coursework, Vibe LMS, and live sessions","question":"10.5 Where do I find the daily live-session schedule?","answer":"The daily live-session schedule is posted in the Announcements section on samagama.in at least 1 hour before the session begins. Log in and check the Announcements section during working hours.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"11_yaksha_chat_related_001","category":"11. Yaksha Chat Related","question":"11.1 I'm unable to type in the chat after clicking Interact with Yaksha — what should I do?","answer":"After logging into your Yaksha portal, if the field shows that you can't type, scroll up to the top of your window and click on the Chat with Yaksha button to activate Yaksha.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"12_vibe_platform_001","category":"12. ViBe Platform","question":"12.1 How do I log in to ViBe?","answer":"Link: https://vibe.vicharanashala.ai/auth. Sign up as a student with the registered mail ID. Log in, check the Notifications tab, Accept the course invite sent for your respective MERN Course.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"12_vibe_platform_002","category":"12. ViBe Platform","question":"12.2 Invite accepted but shows No course enrolled?","answer":"Make sure you are logged in with the correct registered email ID. Check if your college email has multiple aliases and try the correct one. Log out and log in again. Use personal wifi instead of college wifi. Enable third-party cookies in Chrome and set DNS to 8.8.8.8 / 8.8.4.4.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"12_vibe_platform_003","category":"12. ViBe Platform","question":"12.3 Why are videos stuck or repeating?","answer":"This may happen due to ViBe's monitored learning system. Videos must be watched fully and in sequence. Camera and microphone permissions must be enabled. Poor lighting or high background noise can affect playback. Stay on the ViBe tab, keep your camera on, and watch videos in a quiet, well-lit environment.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"12_vibe_platform_004","category":"12. ViBe Platform","question":"12.4 Can I use a mobile or tablet?","answer":"No, only desktop/laptop is supported.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"12_vibe_platform_005","category":"12. ViBe Platform","question":"12.5 I'm experiencing video issues on ViBe. How do I troubleshoot?","answer":"Try these in order: Refresh the page, inspect browser console for errors, log out and log in again, use a different browser, clear browsing data and cache. If issue persists, contact Yaksha with #escalate-ViBe.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"12_vibe_platform_006","category":"12. ViBe Platform","question":"12.6 I completed all videos and quizzes but progress shows less than 100%. What do I do?","answer":"Please verify that you've completed all course items. If not, retry the missed contents again. In the meantime, refresh your browser and log out, clear your browser cache, and log in again.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"12_vibe_platform_007","category":"12. ViBe Platform","question":"12.7 Can I request an exception or bypass the system if I am unhappy with progress evaluation?","answer":"ViBe is built and continuously improved by interns and students themselves. If a learner strongly feels that the regular ViBe flow does not fairly reflect their understanding, there is a formal alternative evaluation path: a three-hour proctored examination based on YouTube video content. Score below 60% means you must join the next cohort. Score above 80% means you have passed.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"12_vibe_platform_008","category":"12. ViBe Platform","question":"12.8 Is the ViBe consent form compulsory?","answer":"Yes — the consent form is compulsory. The platform is designed with proctoring enabled throughout the learning process, which requires access to your webcam and microphone. If you choose not to grant camera and microphone access, you will not be able to proceed with the course.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"12_vibe_platform_009","category":"12. ViBe Platform","question":"12.9 What are penalty scores on ViBe?","answer":"Penalty scores are generated when anomalies are detected during your activity on ViBe (irregular behavior while watching video lessons or attempting quizzes). At present, these penalty scores do not impact your HP or overall performance evaluation.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"12_vibe_platform_010","category":"12. ViBe Platform","question":"12.10 When should I use the Flag option on ViBe, and when should I contact support?","answer":"Use the Flag feature only for course content-related issues (problems with video content or quiz questions). For technical issues, platform errors, login problems, or logistics-related queries, contact Yaksha instead.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"12_vibe_platform_011","category":"12. ViBe Platform","question":"12.11 What is Linear Progression on ViBe?","answer":"Linear progression is enabled for every course on ViBe. Each learner must watch the videos and attempt the quizzes in the exact order they appear. You cannot click on a video or quiz that lies far ahead of your current position.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"12_vibe_platform_012","category":"12. ViBe Platform","question":"12.12 Can I use the left navigation panel to jump ahead?","answer":"No. Although the left navigation panel displays the full list of items, it is meant only as a progress map — not as a jump-to-anywhere menu. Click Next Quiz or Next Lesson as it appears on the right panel.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"12_vibe_platform_013","category":"12. ViBe Platform","question":"12.13 I am seeing a red Access Restricted banner. Is this a bug?","answer":"No. The red Access Restricted banner appears when you try to open an item (video or quiz) before completing all the items that come before it. ViBe automatically returns you to the previous valid content.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"12_vibe_platform_014","category":"12. ViBe Platform","question":"12.14 How do I resolve the Access Restricted error?","answer":"Go back to the left panel and scroll through your course items from the beginning. Look for any item without a completion tick — that is your missed video or quiz. Complete that item, refresh the page. If the issue persists, report to Yaksha with #escalate-ViBe.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"12_vibe_platform_015","category":"12. ViBe Platform","question":"12.15 Why does ViBe sometimes make me re-watch a clip after a quiz?","answer":"If your answer to the check-in quiz didn't go through correctly, ViBe will take you back to the same clip and let you try again. This is part of the design — not a penalty. Re-watches are not recorded against you.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"12_vibe_platform_016","category":"12. ViBe Platform","question":"12.16 What kinds of quiz questions will I see on ViBe?","answer":"ViBe quizzes come in four formats. A small tip: watch the clip first, then answer. Trying to read the question while the clip is still playing splits your attention.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"12_vibe_platform_017","category":"12. ViBe Platform","question":"12.17 Are the same proctoring rules applied to every course on ViBe?","answer":"No. ViBe's proctoring system is modular. Each individual check can be independently switched on or off by the instructor for a given course or cohort. Whether a specific check applies to your course depends entirely on what your instructor has enabled.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"12_vibe_platform_018","category":"12. ViBe Platform","question":"12.18 What does the quiet helper on ViBe actually do?","answer":"While a lesson plays, a small helper runs on your device using your camera and microphone. It checks: a face is visible, only one face is in frame, there is enough light on your face, the room isn't full of voices, and you are looking at the screen.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"12_vibe_platform_019","category":"12. ViBe Platform","question":"12.19 Does ViBe record long videos of me while I'm learning?","answer":"No. ViBe does not continuously record videos of you. The camera and microphone are used for real-time presence checks only. Long recordings of your face or voice are not stored.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"12_vibe_platform_020","category":"12. ViBe Platform","question":"12.20 What is the single most common avoidable mistake learners make?","answer":"Sitting with a window directly behind you during the day. Your camera only sees a dark silhouette where your face should be. The fix is simple: move so the window is to your side or in front of the laptop, not behind you.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"12_vibe_platform_021","category":"12. ViBe Platform","question":"12.21 Why does the lesson keep pausing or restarting even when I'm paying attention?","answer":"If a clip keeps stopping or going back to the start, the cause is almost always something in your environment: your face is too dark, partly out of frame, voices in the background, you switched tabs or went idle, or camera/mic permission dropped.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"12_vibe_platform_022","category":"12. ViBe Platform","question":"12.22 Can I read the quiz questions aloud or mutter to myself while watching?","answer":"It's best not to. The microphone listens for sustained voices in the room, and reading aloud, muttering, or asking a roommate can all be picked up as anomalies. Watch in silence, answer in silence, and chat freely during your breaks between clips.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"12_vibe_platform_023","category":"12. ViBe Platform","question":"12.23 Can I study with a friend on camera since we're learning together?","answer":"In most courses, no. Only you — the registered Learner — should be in the camera frame during a lesson. The helper checks that exactly one face is visible at a time. Group study is best done on a separate call before or after a ViBe lesson, not during it.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"12_vibe_platform_024","category":"12. ViBe Platform","question":"12.24 Will I lose my progress if I clear my browser or reinstall it?","answer":"No. Your progress is saved on the server, tied to your registered email — not on your browser or your computer. Refreshing, clearing cache, switching browsers, or reinstalling your browser will not wipe your progress.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"12_vibe_platform_025","category":"12. ViBe Platform","question":"12.25 Is there a recommended daily learning rhythm on ViBe?","answer":"Yes — small, regular sessions work far better than long marathon sessions. Show up daily, even if only for thirty minutes. Take breaks between clips, not during them. Treat each quiz as a gentle check-in, not a high-stakes test.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"12_vibe_platform_026","category":"12. ViBe Platform","question":"12.26 What should my study corner look like before I start a ViBe session?","answer":"A ViBe-friendly study spot needs: light in front of your face (a lamp or window facing you, never behind), just you in the camera frame, and a reasonably quiet room (no TV, no music with words, no one else on a call nearby).","source":"samagama_faq","chunk_type":"faq"},
  {"id":"13_team_formation_001","category":"13. Team Formation","question":"13.1 Is team formation compulsory?","answer":"Yes. All projects in Phase 2 and Phase 3 must be completed in teams. Every participant is required to be part of a team.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"13_team_formation_002","category":"13. Team Formation","question":"13.2 What is the size of a team?","answer":"The team size is fixed at four members. This is mandatory — you cannot have fewer or more members in a team at the time of final formation.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"13_team_formation_003","category":"13. Team Formation","question":"13.3 How are teams formed?","answer":"For students who joined on May 15 and 16: Teams were formed through a structured activity. For students joining later: Teams will be randomly assigned by the administration.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"13_team_formation_004","category":"13. Team Formation","question":"13.4 I started on May 15/16 but couldn't form a team during the activity. What happens now?","answer":"You will be randomly assigned to a team.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"13_team_formation_005","category":"13. Team Formation","question":"13.5 There was a typo in our email addresses during team formation. Can we fix it?","answer":"No action is required from your side. The administration will verify and match email IDs with names before finalizing and locking teams.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"13_team_formation_006","category":"13. Team Formation","question":"13.6 I formed a team with only two members. Will it be considered?","answer":"No. Teams with fewer than four members will be expanded by adding additional members to make a final team of four.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"13_team_formation_007","category":"13. Team Formation","question":"13.7 What if a team member leaves or becomes ineligible during Phase 1?","answer":"The administration will attempt to assign a replacement member. If no replacement is found, you may continue as a team of three. You must inform the admin immediately.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"13_team_formation_008","category":"13. Team Formation","question":"13.8 Can I form a team with someone from my own college?","answer":"No. Teams must consist of members from different institutions to encourage networking. Exception: Students from the same institution but different campuses/locations may be allowed.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"13_team_formation_009","category":"13. Team Formation","question":"13.9 Can I form a team with students from my IIT MBS cohort?","answer":"No. You are encouraged to collaborate with participants outside your existing cohort.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"13_team_formation_010","category":"13. Team Formation","question":"13.10 Can we change our team name after submission?","answer":"Yes, team names are tentative and can be changed. However, due to operational constraints, frequent changes are discouraged.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"13_team_formation_011","category":"13. Team Formation","question":"13.11 What if multiple teams choose the same name?","answer":"Teams will be distinguished using suffixes (e.g., Team X-1, Team X-2, etc.).","source":"samagama_faq","chunk_type":"faq"},
  {"id":"13_team_formation_012","category":"13. Team Formation","question":"13.12 What should I do if I face issues within my team?","answer":"Report any concerns immediately to your assigned scholar/mentor. Maintaining a safe and respectful environment is a priority.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"13_team_formation_013","category":"13. Team Formation","question":"13.13 How will I know who my mentor is?","answer":"Your mentor will be the scholar assigned to the project your team is working on.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"13_team_formation_014","category":"13. Team Formation","question":"13.14 When will I know my team details?","answer":"Team details are announced in the Announcements section on samagama.in. Log in and check regularly during working hours.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"13_team_formation_015","category":"13. Team Formation","question":"13.15 I received a team list email but my name is not included. What should I do?","answer":"Team announcements are phased, so your name may appear in a later list. If your entire cohort has moved to team activities and you are still unassigned, raise the issue on Yaksha or contact a scholar.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"13_team_formation_016","category":"13. Team Formation","question":"13.16 We selected Project X as our top priority but were assigned Project Y. Can we change it?","answer":"No. Project assignments are final and cannot be changed. Allocation is done to ensure balanced distribution across projects.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"13_team_formation_017","category":"13. Team Formation","question":"13.17 I just started the internship. Can I form my own team now?","answer":"No. For later cohorts, teams will be randomly assigned. Please wait for the official communication.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"13_team_formation_018","category":"13. Team Formation","question":"13.18 When do team activities begin?","answer":"Team-based work begins in Phase 2. During Phase 1 (online coursework), you do not need to worry about team activities.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"13_team_formation_019","category":"13. Team Formation","question":"13.19 Can I request a specific teammate after teams are assigned?","answer":"No. Team assignments are final and requests for changes are not entertained.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"13_team_formation_020","category":"13. Team Formation","question":"13.20 What happens if a team member is inactive or not contributing?","answer":"You should report the issue to your mentor/scholar early. Prolonged inactivity may lead to administrative intervention.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"13_team_formation_021","category":"13. Team Formation","question":"13.21 Can I switch teams if there are conflicts?","answer":"Team switches are not allowed except in exceptional, admin-approved cases involving serious concerns.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"13_team_formation_022","category":"13. Team Formation","question":"13.22 Will team performance affect individual evaluation?","answer":"Yes. While some components may be individual, team deliverables are a key part of evaluation.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"13_team_formation_023","category":"13. Team Formation","question":"13.23 How will communication happen within teams?","answer":"Teams self-organise internal coordination over LinkedIn or email only, limited to their own team members. WhatsApp is not permitted to create a team WhatsApp group — a group of that form will lead to immediate termination of the internship.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"13_team_formation_024","category":"13. Team Formation","question":"13.24 What if I miss the team allocation announcement?","answer":"All programme updates are posted in the Announcements section on samagama.in. Log in and check regularly during working hours — this is the only channel for official notifications.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"13_team_formation_025","category":"13. Team Formation","question":"13.25 Can a team be dissolved and reformed?","answer":"No. Once finalized, teams are locked and cannot be dissolved.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"13_team_formation_026","category":"13. Team Formation","question":"13.26 What happens if I drop out of the internship?","answer":"Your team will be adjusted accordingly, and the remaining members may continue as a team of three or receive a replacement.","source":"samagama_faq","chunk_type":"faq"},
  {"id":"13_team_formation_027","category":"13. Team Formation","question":"13.27 Will we get time to get to know our teammates before Phase 2?","answer":"Yes. There is typically a buffer period before Phase 2 where teams can connect and prepare.","source":"samagama_faq","chunk_type":"faq"}
];

async function importFAQs() {
  await mongoose.connect(process.env.MONGO_URI || 'mongodb://localhost:27017/qa-platform');
  console.log(`Starting bulk import of ${faqs.length} FAQs...`);

  let inserted = 0;
  let skipped = 0;
  let errors = 0;

  for (const item of faqs) {
    try {
      const existing = await FAQ.findOne({ question: item.question });
      if (existing) {
        console.log(`  SKIP: ${item.question.slice(0, 50)}... (already exists)`);
        skipped++;
        continue;
      }

      const faq = await FAQ.create({
        question: item.question,
        answer: item.answer,
        category: item.category,
        tags: [item.source],
        source: item.source,
        createdBy: null
      });

      try {
        await insertFAQVector(faq);
      } catch (vecErr) {
        logger.error(`Vector sync failed for ${faq._id}: ${vecErr.message}`);
      }

      console.log(`  INSERTED: ${item.question.slice(0, 50)}...`);
      inserted++;
    } catch (err) {
      console.error(`  ERROR: ${item.question.slice(0, 50)}...: ${err.message}`);
      errors++;
    }
  }

  console.log(`\n=== Import complete ===`);
  console.log(`Inserted: ${inserted}`);
  console.log(`Skipped (already exist): ${skipped}`);
  console.log(`Errors: ${errors}`);

  if (inserted > 0) {
    console.log('\nRebuilding FAQ corpus...');
    const allFaqs = await FAQ.find();
    const texts = allFaqs.map(f => buildFAQText(f));
    rebuildCorpus(CORPUS_FAQ, texts);
    console.log(`Corpus rebuilt with ${texts.length} documents`);
  }

  await mongoose.disconnect();
  console.log('Done.');
}

importFAQs().then(() => process.exit(0)).catch(err => {
  console.error('Fatal error:', err);
  process.exit(1);
});
